# Generated by Django 2.2.5 on 2020-05-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200503_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(choices=[('International', 'international'), ('Local', 'local'), ('Politics', 'politics'), ('Agriculture', 'agriculture'), ('Oil', 'oil'), ('Finance', 'Finance'), ('Health', 'health'), ('Sports', 'sports'), ('Fashion', 'fashion'), ('Tech', 'tech'), ('Weather', 'weather')], max_length=100, null=True, to='news.Category'),
        ),
    ]
