# Generated by Django 2.2.5 on 2020-05-04 13:19

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200503_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('International', 'international'), ('Local', 'local'), ('Politics', 'politics'), ('Agriculture', 'agriculture'), ('Oil', 'oil'), ('Finance', 'Finance'), ('Health', 'health'), ('Sports', 'sports'), ('Fashion', 'fashion'), ('Tech', 'tech'), ('Weather', 'weather')], max_length=100, null=True, verbose_name=news.models.Category),
        ),
    ]
