# Generated by Django 2.2.5 on 2020-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
