# Generated by Django 2.2.5 on 2020-05-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200505_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
